// AUTO-GENERATED from UK_Wreck_Dives_Database.xlsx — shared data + helpers
const SITES=[
{
"slug": "sms-markgraf",
"n": "SMS Markgraf",
"wreck": "SMS Markgraf",
"r": "Scapa Flow, Orkney",
"lat": 58.872,
"lon": -3.17,
"td": "none",
"hwi": 8.0,
"nd": false,
"type": "German WWI battleship (König class)",
"year": "1919 (scuttled)",
"length": 175,
"minD": 24,
"maxD": 45,
"gas": "Trimix (e.g. 21/35)",
"lvl": "Technical (40m+)",
"temp": "6–14",
"best": "May (viz) & Sep–Oct",
"curr": "Low",
"enter": "Any state – sheltered",
"tidal": "No tidal constraints on the German Fleet",
"viz": "6–15m",
"prot": "Scheduled Monument; within Scapa Flow Historic MPA (Nov 2025) – no removal",
"access": "Hard boat / liveaboard from Stromness",
"chamber": "Orkney Hyperbaric Trust, Stromness (24/7)",
"halifax": "≈475 to Scrabster + ferry",
"fill": "Scapa Scuba, Stromness / onboard charter (air, nitrox, trimix)",
"fillsite": "≈8 (steam)",
"notes": "Deepest & most intact of the 3 battleships; headline features (casemates, rangefinders) sit deep. On her starboard side."
},
{
"slug": "sms-kronprinz-wilhelm",
"n": "SMS Kronprinz Wilhelm",
"wreck": "SMS Kronprinz Wilhelm",
"r": "Scapa Flow, Orkney",
"lat": 58.876,
"lon": -3.171,
"td": "none",
"hwi": 8.0,
"nd": false,
"type": "German WWI battleship (König class)",
"year": "1919 (scuttled)",
"length": 175,
"minD": 12,
"maxD": 38,
"gas": "EAN28 / Trimix",
"lvl": "Advanced–Technical",
"temp": "6–14",
"best": "May (viz) & Sep–Oct",
"curr": "Low",
"enter": "Any state – sheltered",
"tidal": "No tidal constraints",
"viz": "6–15m",
"prot": "Scheduled Monument; within Scapa Flow Historic MPA – no removal",
"access": "Hard boat / liveaboard from Stromness",
"chamber": "Orkney Hyperbaric Trust, Stromness (24/7)",
"halifax": "≈475 to Scrabster + ferry",
"fill": "Scapa Scuba, Stromness / onboard charter",
"fillsite": "≈8 (steam)",
"notes": "Most accessible battleship – inverted, bilge keel/port side rises to ~12m. 'Shake hands with a battleship at 15m.'"
},
{
"slug": "sms-coln",
"n": "SMS Cöln",
"wreck": "SMS Cöln",
"r": "Scapa Flow, Orkney",
"lat": 58.884,
"lon": -3.155,
"td": "none",
"hwi": 8.0,
"nd": false,
"type": "German WWI light cruiser",
"year": "1919 (scuttled)",
"length": 155,
"minD": 22,
"maxD": 36,
"gas": "EAN28",
"lvl": "Advanced (deep)",
"temp": "6–14",
"best": "May (viz) & Sep–Oct",
"curr": "Low",
"enter": "Any state – sheltered",
"tidal": "No tidal constraints",
"viz": "6–15m",
"prot": "Scheduled Monument; within Scapa Flow Historic MPA – no removal",
"access": "Hard boat / liveaboard from Stromness",
"chamber": "Orkney Hyperbaric Trust, Stromness (24/7)",
"halifax": "≈475 to Scrabster + ferry",
"fill": "Scapa Scuba, Stromness / onboard charter",
"fillsite": "≈8 (steam)",
"notes": "Most intact of the four cruisers; long swim along an unbroken hull. On starboard side."
},
{
"slug": "sms-karlsruhe",
"n": "SMS Karlsruhe",
"wreck": "SMS Karlsruhe",
"r": "Scapa Flow, Orkney",
"lat": 58.885,
"lon": -3.198,
"td": "none",
"hwi": 8.0,
"nd": false,
"type": "German WWI light cruiser",
"year": "1919 (scuttled)",
"length": 150,
"minD": 14,
"maxD": 27,
"gas": "EAN32",
"lvl": "Recreational (AOW+)",
"temp": "6–14",
"best": "May (viz) & Sep–Oct",
"curr": "Low",
"enter": "Any state – sheltered",
"tidal": "No tidal constraints",
"viz": "6–15m",
"prot": "Scheduled Monument; within Scapa Flow Historic MPA – no removal",
"access": "Hard boat / liveaboard from Stromness",
"chamber": "Orkney Hyperbaric Trust, Stromness (24/7)",
"halifax": "≈475 to Scrabster + ferry",
"fill": "Scapa Scuba, Stromness / onboard charter",
"fillsite": "≈8 (steam)",
"notes": "Shallowest cruiser; heavily broken so the most marine-life rich – a good first Scapa wreck."
},
{
"slug": "sms-brummer",
"n": "SMS Brummer",
"wreck": "SMS Brummer",
"r": "Scapa Flow, Orkney",
"lat": 58.884,
"lon": -3.152,
"td": "none",
"hwi": 8.0,
"nd": false,
"type": "German WWI mine-laying cruiser",
"year": "1919 (scuttled)",
"length": 140,
"minD": 22,
"maxD": 36,
"gas": "EAN28",
"lvl": "Advanced (deep)",
"temp": "6–14",
"best": "May (viz) & Sep–Oct",
"curr": "Low",
"enter": "Any state – sheltered",
"tidal": "No tidal constraints",
"viz": "6–15m",
"prot": "Scheduled Monument; within Scapa Flow Historic MPA – no removal",
"access": "Hard boat / liveaboard from Stromness",
"chamber": "Orkney Hyperbaric Trust, Stromness (24/7)",
"halifax": "≈475 to Scrabster + ferry",
"fill": "Scapa Scuba, Stromness / onboard charter",
"fillsite": "≈8 (steam)",
"notes": "Often rated the single best dive in the Flow – intact bow, vivid life. On starboard side; deck sections peeling (deteriorating)."
},
{
"slug": "hms-royal-oak",
"n": "HMS Royal Oak",
"wreck": "HMS Royal Oak",
"r": "Scapa Flow, Orkney",
"lat": 58.931,
"lon": -2.984,
"td": "nd",
"hwi": 0,
"nd": true,
"type": "Royal Navy battleship (Revenge class)",
"year": "1939",
"length": "189",
"minD": "–",
"maxD": 33,
"gas": "N/A – diving prohibited",
"lvl": "N/A",
"temp": "6–14",
"best": "N/A",
"curr": "Low",
"enter": "N/A",
"tidal": "N/A",
"viz": "–",
"prot": "CONTROLLED SITE (Protection of Military Remains Act) – ALL diving banned. War grave (~835 lost).",
"access": "None – marked by memorial buoy",
"chamber": "Orkney Hyperbaric Trust, Stromness",
"halifax": "≈475 to Scrabster + ferry",
"fill": "N/A",
"fillsite": "N/A",
"notes": "Listed as a WARNING: torpedoed by U-47, 14 Oct 1939. Highest PMRA protection – diving/interference is a criminal offence. Still leaks oil."
},
{
"slug": "ss-somali",
"n": "SS Somali",
"wreck": "SS Somali",
"r": "Farne Islands, Northumberland",
"lat": 55.553,
"lon": -1.607,
"td": "slack",
"hwi": 3.5,
"nd": false,
"type": "Passenger-cargo steamer (WWII bomb casualty)",
"year": "1941",
"length": 137,
"minD": 20,
"maxD": 30,
"gas": "EAN28–32",
"lvl": "Advanced (deep)",
"temp": "6–15",
"best": "May–Oct (viz best Jun–Sep)",
"curr": "Medium",
"enter": "Slack advisable",
"tidal": "Some tidal movement; slack advisable",
"viz": "up to 20m (among UK's clearest)",
"prot": "Privately owned wreck (not designated)",
"access": "Hard boat from Seahouses",
"chamber": "Via 999 / Coastguard (BHA duty chamber)",
"halifax": "≈150",
"fill": "Sovereign Diving, Seahouses (air, nitrox)",
"fillsite": "≈4",
"notes": "Bombed off Blyth 1941; burned & broke up off Beadnell Point. Big boilers, engine, 12-pdr AA gun. Salvaged over years but takes several dives."
},
{
"slug": "chris-christensen",
"n": "Chris Christensen",
"wreck": "Chris Christensen",
"r": "Farne Islands, Northumberland",
"lat": 55.639,
"lon": -1.604,
"td": "essential",
"hwi": 3.5,
"nd": false,
"type": "Danish steamship (grounded 1915)",
"year": "1915",
"length": "~90",
"minD": 20,
"maxD": 33,
"gas": "EAN28",
"lvl": "Advanced (deep)",
"temp": "6–15",
"best": "May–Oct (viz best Jun–Sep)",
"curr": "Strong",
"enter": "Slack essential (≈2h after LW Seahouses)",
"tidal": "Slack essential; strong tides, downcurrents reported",
"viz": "up to 20m",
"prot": "Not protected",
"access": "Hard boat from Seahouses",
"chamber": "Via 999 / Coastguard (BHA duty chamber)",
"halifax": "≈150",
"fill": "Sovereign Diving, Seahouses (air, nitrox)",
"fillsite": "≈5",
"notes": "Aground on Longstone Ends 1915. Broken but scenic – boilers, engine, girders, iron steering wheel. Sloping reef eases the ascent. Conger, wolffish, ling."
},
{
"slug": "ss-glanmire",
"n": "SS Glanmire",
"wreck": "SS Glanmire",
"r": "St Abbs & Eyemouth, Berwickshire",
"lat": 55.902,
"lon": -2.132,
"td": "slack",
"hwi": 3.5,
"nd": false,
"type": "Steamship (sank 1912)",
"year": "1912",
"length": "~85",
"minD": 20,
"maxD": 30,
"gas": "EAN28–32",
"lvl": "Advanced (deep)",
"temp": "6–14",
"best": "Jun–Sep",
"curr": "Low–Medium",
"enter": "Slack water",
"tidal": "Slack water; 300m offshore, sheltered",
"viz": "5–15m",
"prot": "Within Berwickshire Marine Reserve – no removal of marine life",
"access": "Hard boat from Eyemouth",
"chamber": "Via 999 / Coastguard",
"halifax": "≈172",
"fill": "Marine Quest / The Harbourside, Eyemouth (air, nitrox, trimix)",
"fillsite": "≈5",
"notes": "One of the area's best – wolffish, conger, big fish shoals. NB deeper local tech wrecks (HMS Pathfinder ~68m, U-12) are war graves – respect, no penetration/removal."
},
{
"slug": "hmhs-rohilla",
"n": "HMHS Rohilla",
"wreck": "HMHS Rohilla",
"r": "Whitby, North Yorkshire",
"lat": 54.4996,
"lon": -0.5893,
"td": "none",
"hwi": 3.5,
"nd": false,
"type": "Hospital ship (wrecked in storm 1914)",
"year": "1914",
"length": 140,
"minD": 6,
"maxD": 16,
"gas": "Air / EAN32",
"lvl": "Recreational (all levels)",
"temp": "6–16",
"best": "Jun–Sep (after a dry spell)",
"curr": "Low",
"enter": "Any state (avoid spring tides)",
"tidal": "Small tidal range – diveable most states; avoid springs",
"viz": "2–8m (poor after rain – Esk runoff)",
"prot": "Local syndicate – no recovery by custom",
"access": "RIB / club boat from Whitby harbour slipway",
"chamber": "Via 999 / Coastguard",
"halifax": "≈62",
"fill": "No public fill in Whitby – fill at Academy Divers, Halifax (air/nitrox/trimix) before travel, or use a club compressor",
"fillsite": "≈62 (fill inland)",
"notes": "Grounded on Whitby Rock 30 Oct 1914; ~85 lives lost. Shallow & scattered – 4 boilers, shaft. Great training / off-gassing dive right by the harbour."
},
{
"slug": "uc-70",
"n": "UC-70",
"wreck": "UC-70",
"r": "Whitby, North Yorkshire",
"lat": 54.527,
"lon": -0.669,
"td": "essential",
"hwi": 3.5,
"nd": false,
"type": "German WWI minelaying U-boat (UC-II)",
"year": "1918",
"length": "~50",
"minD": 22,
"maxD": 24,
"gas": "EAN32",
"lvl": "Advanced",
"temp": "6–16",
"best": "Jun–Sep (after a dry spell)",
"curr": "Strong",
"enter": "Slack only (≈2h after HW/LW Whitby)",
"tidal": "Slack essential; strong tides",
"viz": "2–8m",
"prot": "Sunk 1918 – not a designated war grave, but treat with respect",
"access": "RIB / club boat from Whitby (~3 mi up coast)",
"chamber": "Via 999 / Coastguard",
"halifax": "≈62",
"fill": "As Rohilla – fill at Academy Divers, Halifax before travel",
"fillsite": "≈62 (fill inland)",
"notes": "Depth-charged/rammed 1918. Sits near-upright with slight port list; deck gun intact & pointing up, open hatches. No heavy deco – a good step toward deeper wrecks."
},
{
"slug": "the-kimya",
"n": "The Kimya",
"wreck": "MV Kimya",
"r": "Anglesey, North Wales",
"lat": 53.159,
"lon": -4.449,
"td": "none",
"hwi": 9.0,
"nd": false,
"type": "Steel tanker (capsized 1991)",
"year": "1991",
"length": 73,
"minD": 6,
"maxD": 15,
"gas": "Air / EAN32",
"lvl": "Recreational (novice-friendly)",
"temp": "8–16",
"best": "Apr–Oct",
"curr": "Low",
"enter": "Any state (little current)",
"tidal": "Diveable all states of tide",
"viz": "3–10m",
"prot": "Not protected",
"access": "RIB from Trearddur Bay / Holyhead",
"chamber": "Via 999 / Coastguard",
"halifax": "≈135",
"fill": "Anglesey Divers, Holyhead (air 300 bar, nitrox)",
"fillsite": "≈10",
"notes": "Sank 16 mi SW of Holyhead 1991 (sunflower-oil cargo); salvaged & re-sunk on sand. Rudder stands 7m. Ideal season-opener / training wreck, upright."
},
{
"slug": "ss-missouri",
"n": "SS Missouri",
"wreck": "SS Missouri",
"r": "Anglesey, North Wales",
"lat": 53.32,
"lon": -4.7,
"td": "slack",
"hwi": 9.0,
"nd": false,
"type": "Steamship (ran aground 1886)",
"year": "1886",
"length": 130,
"minD": 5,
"maxD": 15,
"gas": "Air / EAN32",
"lvl": "Recreational",
"temp": "8–16",
"best": "Apr–Oct",
"curr": "Medium",
"enter": "Slack advisable (near North Stack tide race)",
"tidal": "Slack advisable; broken & shallow",
"viz": "3–10m",
"prot": "Not protected",
"access": "RIB from Trearddur Bay (~15 min)",
"chamber": "Via 999 / Coastguard",
"halifax": "≈135",
"fill": "Anglesey Divers, Holyhead (air, nitrox)",
"fillsite": "≈4",
"notes": "Aground near North Stack 1886. Broken & shallow but scenic with lots of life; within a 15-min RIB ride of Trearddur Bay."
},
{
"slug": "james-eagan-layne",
"n": "James Eagan Layne",
"wreck": "James Eagan Layne",
"r": "Whitsand Bay / Plymouth",
"lat": 50.3268,
"lon": -4.2453,
"td": "none",
"hwi": 5.5,
"nd": false,
"type": "US WWII Liberty ship (torpedoed 1945)",
"year": "1945",
"length": 130,
"minD": 8,
"maxD": 24,
"gas": "EAN32",
"lvl": "Recreational (AOW+)",
"temp": "8–17",
"best": "May–Oct",
"curr": "Low",
"enter": "Any state of tide",
"tidal": "Diveable any state",
"viz": "3–10m",
"prot": "War casualty but not designated",
"access": "Hard boat from Plymouth (Mount Batten / Queen Anne's Battery)",
"chamber": "DDRC Healthcare, Plymouth",
"halifax": "≈335",
"fill": "In Deep Dive Centre or Aquanauts, Plymouth (air, nitrox, trimix)",
"fillsite": "≈7",
"notes": "Torpedoed by U-1195, 21 Mar 1945; sank upright in Whitsand Bay. Bow ~8m, holds accessible. UK's most famous Liberty ship – ideal wreck-spec dive."
},
{
"slug": "hms-scylla",
"n": "HMS Scylla",
"wreck": "HMS Scylla",
"r": "Whitsand Bay / Plymouth",
"lat": 50.335,
"lon": -4.246,
"td": "none",
"hwi": 5.5,
"nd": false,
"type": "RN Leander frigate (scuttled as reef 2004)",
"year": "2004",
"length": 113,
"minD": 9,
"maxD": 24,
"gas": "EAN32",
"lvl": "Recreational (AOW+)",
"temp": "8–17",
"best": "May–Oct",
"curr": "Low–Medium",
"enter": "Not slack-free; avoid springs & busy weekends",
"tidal": "Some tide; visibility silts with diver traffic",
"viz": "3–10m",
"prot": "No penetration permitted (unsafe since 2014) – NMA guidance",
"access": "Hard boat from Plymouth",
"chamber": "DDRC Healthcare, Plymouth",
"halifax": "≈335",
"fill": "In Deep / Aquanauts, Plymouth",
"fillsite": "≈7",
"notes": "Europe's first artificial reef, sunk 27 Mar 2004; 250+ species recorded. Multi-level – superb for training & photography. Do NOT penetrate the interior."
},
{
"slug": "countess-of-erne",
"n": "Countess of Erne",
"wreck": "Countess of Erne",
"r": "Portland & Weymouth, Dorset",
"lat": 50.573,
"lon": -2.43,
"td": "none",
"hwi": 6.5,
"nd": false,
"type": "Iron paddle steamer / coal hulk",
"year": "1935",
"length": 74,
"minD": 7,
"maxD": 15,
"gas": "Air / EAN32",
"lvl": "Recreational (novice/training)",
"temp": "8–18",
"best": "May–Oct",
"curr": "Low (gentle)",
"enter": "Any state (sheltered in harbour)",
"tidal": "Diveable all states; sheltered by breakwater",
"viz": "3–8m (silty)",
"prot": "Not protected",
"access": "Hard boat from Portland Marina / free slip at Castletown (harbour permit needed)",
"chamber": "DDRC Plymouth / Poole via 999-Coastguard",
"halifax": "≈295",
"fill": "Portland Gas Shack & SkinDeeper (air, nitrox, trimix, 300 bar)",
"fillsite": "≈2",
"notes": "Broke moorings & sank against the breakwater 1935. Upright, 3 open holds (silty swim-throughs). Deteriorating & 'spiky' – carry an SMB (harbour-entrance current close by)."
},
{
"slug": "m2-submarine",
"n": "M2 Submarine",
"wreck": "HMS M2",
"r": "Portland & Weymouth, Dorset",
"lat": 50.545,
"lon": -2.56,
"td": "essential",
"hwi": 6.5,
"nd": false,
"type": "RN submarine (aircraft-carrier sub, sank 1932)",
"year": "1932",
"length": 90,
"minD": 30,
"maxD": 36,
"gas": "EAN28",
"lvl": "Advanced (deep)",
"temp": "8–17",
"best": "May–Oct",
"curr": "Medium–Strong",
"enter": "Slack water",
"tidal": "Slack water essential",
"viz": "3–10m",
"prot": "War grave (~60 lost) – dive with respect, no penetration/removal",
"access": "Hard boat from Portland / Weymouth",
"chamber": "DDRC Plymouth / Poole via Coastguard",
"halifax": "≈295",
"fill": "Portland Gas Shack & SkinDeeper",
"fillsite": "≈6",
"notes": "Sank Jan 1932, probably flooded via the open hangar (doors still open). Iconic – launched a seaplane by catapult. All hands lost; treat as a war grave."
},
{
"slug": "ss-salsette",
"n": "SS Salsette",
"wreck": "SS Salsette",
"r": "Portland & Weymouth, Dorset",
"lat": 50.52,
"lon": -2.76,
"td": "slack",
"hwi": 6.5,
"nd": false,
"type": "P&O ocean liner (torpedoed 1917)",
"year": "1917",
"length": 134,
"minD": 27,
"maxD": 45,
"gas": "Trimix (e.g. 25/25)",
"lvl": "Technical (40m+)",
"temp": "8–16",
"best": "Jun–Sep",
"curr": "Medium",
"enter": "Slack water",
"tidal": "Slack water; ~15 mi offshore in Lyme Bay",
"viz": "5–12m",
"prot": "War casualty, not designated",
"access": "Hard boat from Portland / Weymouth",
"chamber": "DDRC Plymouth / Poole via Coastguard",
"halifax": "≈295",
"fill": "Portland Gas Shack & SkinDeeper (trimix)",
"fillsite": "≈15",
"notes": "Torpedoed by UB-40, 20 Jul 1917; 15 crew lost. Intact on her side at ~45m – a classic Dorset technical wreck with fine fittings."
},
{
"slug": "aeolian-sky",
"n": "Aeolian Sky",
"wreck": "Aeolian Sky",
"r": "Portland & Weymouth, Dorset",
"lat": 50.553,
"lon": -2.352,
"td": "slack",
"hwi": 6.5,
"nd": false,
"type": "Greek cargo ship (collision 1979)",
"year": "1979",
"length": 157,
"minD": 25,
"maxD": 30,
"gas": "EAN28–32",
"lvl": "Advanced (deep)",
"temp": "8–17",
"best": "May–Oct",
"curr": "Medium",
"enter": "Slack water",
"tidal": "Slack water",
"viz": "3–10m",
"prot": "Not protected",
"access": "Hard boat from Portland / Weymouth",
"chamber": "DDRC Plymouth / Poole via Coastguard",
"halifax": "≈295",
"fill": "Portland Gas Shack & SkinDeeper",
"fillsite": "≈5",
"notes": "Sank 1979 after a collision, general cargo (incl. Land Rovers). Huge & broken but impressive – a big single dive. Silty."
},
{
"slug": "ss-breda",
"n": "SS Breda",
"wreck": "SS Breda",
"r": "Oban, Argyll",
"lat": 56.476,
"lon": -5.418,
"td": "none",
"hwi": 1.0,
"nd": false,
"type": "Dutch cargo ship (bombed 1940)",
"year": "1940",
"length": 122,
"minD": 9,
"maxD": 30,
"gas": "EAN28–32",
"lvl": "Recreational (all levels)",
"temp": "7–15",
"best": "Apr–Oct (spring best viz)",
"curr": "Low (non-tidal bay)",
"enter": "Any state (wait 2h after ebb begins after heavy rain)",
"tidal": "Effectively non-tidal in Ardmucknish Bay",
"viz": "5–15m (silt in holds)",
"prot": "Not protected",
"access": "Hard boat / RIB from Oban (Port Gallanach), Ardmucknish Bay",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈340",
"fill": "Puffin Dive Centre, Oban (air; nitrox by arrangement)",
"fillsite": "≈7",
"notes": "Bombed 1940 (near-miss); cargo incl. aircraft, vehicles, motorcycles, cement. Upright, bow ~9m to seabed ~30m – suits everyone. Superstructure wire-swept in the 60s."
},
{
"slug": "ss-thesis",
"n": "SS Thesis",
"wreck": "SS Thesis",
"r": "Oban, Argyll",
"lat": 56.499,
"lon": -5.691,
"td": "essential",
"hwi": 1.0,
"nd": false,
"type": "Iron screw steamer (ran aground 1889)",
"year": "1889",
"length": 51,
"minD": 20,
"maxD": 32,
"gas": "EAN28–32",
"lvl": "Advanced (deep, experienced)",
"temp": "7–15",
"best": "Apr–Oct",
"curr": "Strong",
"enter": "Slack – middle 4 hrs of the flooding tide",
"tidal": "Slack/flooding tide only; tide whips round Rubha an Ridire and can turn fast – experienced divers only",
"viz": "10–20m (often excellent – open hull lets light in)",
"prot": "Not protected",
"access": "Hard boat / day-boat from Oban (Sound of Mull, ~13.5 NM)",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈340",
"fill": "Puffin Dive Centre, Oban (air; nitrox by arrangement)",
"fillsite": "≈16",
"notes": "Ran aground at Inninmore Point 1889. Hull plates blasted/fallen away so you can swim the length below deck level with light pouring in – very photogenic. Often done as the 2nd dive heading back to Oban."
},
{
"slug": "ss-shuna",
"n": "SS Shuna",
"wreck": "SS Shuna",
"r": "Oban, Argyll",
"lat": 56.53,
"lon": -5.83,
"td": "none",
"hwi": 1.0,
"nd": false,
"type": "Glasgow screw steamer (wrecked 1913)",
"year": "1913",
"length": 73,
"minD": 26,
"maxD": 32,
"gas": "EAN28–32",
"lvl": "Advanced (deep)",
"temp": "7–15",
"best": "Apr–Oct",
"curr": "Low",
"enter": "Any state (currents <½ kt)",
"tidal": "Diveable all states; gentle NW/SE current",
"viz": "5–12m (silty – careful finning)",
"prot": "Not protected",
"access": "Hard boat from Oban (Sound of Mull)",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈340",
"fill": "Puffin Dive Centre, Oban (air; nitrox by arrangement)",
"fillsite": "≈21",
"notes": "Coal/iron cargo, Glasgow to Gothenburg; struck the Grey Rocks 1913. Upright and largely intact, bows pointing SE. Known as the ‘shitty Shuna’ for its silt – stay off the deck and mind your fins."
},
{
"slug": "madam-alice",
"n": "Madam Alice",
"wreck": "Madam Alice",
"r": "Oban, Argyll",
"lat": 56.452,
"lon": -5.485,
"td": "slack",
"hwi": 1.0,
"nd": false,
"type": "Steamer (lost 1918)",
"year": "1918",
"length": 46,
"minD": 32,
"maxD": 38,
"gas": "EAN28",
"lvl": "Advanced (deep)",
"temp": "7–15",
"best": "Apr–Oct",
"curr": "Low–Medium",
"enter": "Slack advisable",
"tidal": "On a gently sloping seabed; shallowest point ~32m",
"viz": "5–12m",
"prot": "Not protected",
"access": "Hard boat / RIB from Oban, Ardmucknish Bay",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈340",
"fill": "Puffin Dive Centre, Oban (air; nitrox by arrangement)",
"fillsite": "≈8",
"notes": "Fully intact ~150ft (46m) vessel lost 1918, marked by a can visible at low water (needs echo-sounding to locate). A deeper, quieter alternative to the nearby Breda. Depths approximate – confirm with Puffin/skipper."
},
{
"slug": "ss-hispania",
"n": "SS Hispania",
"wreck": "SS Hispania",
"r": "Sound of Mull (Lochaline)",
"lat": 56.582,
"lon": -5.987,
"td": "essential",
"hwi": 1.0,
"nd": false,
"type": "Swedish steamship (grounded 1954)",
"year": "1954",
"length": 72,
"minD": 15,
"maxD": 30,
"gas": "EAN28–32",
"lvl": "Advanced (deep)",
"temp": "7–15",
"best": "Apr–Oct",
"curr": "Medium–Strong",
"enter": "Slack water essential (spring HW/LW slack)",
"tidal": "Slack water essential; strong tides",
"viz": "5–15m",
"prot": "Not protected",
"access": "Hard boat from Lochaline",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈380",
"fill": "Lochaline Dive Centre (air, nitrox); charter compressor for air",
"fillsite": "≈4",
"notes": "Ran onto a reef Dec 1954; the captain went down with the ship. Upright, slight starboard list, near-intact and smothered in life – rated one of Scotland's best scenic wrecks. Decks 15–20m."
},
{
"slug": "ss-rondo",
"n": "SS Rondo",
"wreck": "SS Rondo",
"r": "Sound of Mull (Lochaline)",
"lat": 56.538,
"lon": -5.912,
"td": "essential",
"hwi": 1.0,
"nd": false,
"type": "Cargo steamer (wrecked 1935)",
"year": "1935",
"length": 80,
"minD": 8,
"maxD": 50,
"gas": "Trimix (deep) / EAN32 (shallow)",
"lvl": "Advanced–Technical",
"temp": "7–15",
"best": "Apr–Oct",
"curr": "Strong",
"enter": "Slack or ebb",
"tidal": "Slack/ebb; strong currents on the wreck",
"viz": "5–15m (can be gin-clear)",
"prot": "Not protected",
"access": "Hard boat from Lochaline",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈380",
"fill": "Lochaline Dive Centre (air, nitrox); charter compressor",
"fillsite": "≈3",
"notes": "Sits almost vertical – rudder near surface (~6–10m), bow ~50m. 'Three dives in one': deep wreck + reef + off-gas on ascent. History of accidents – respect the current."
},
{
"slug": "ss-aurania",
"n": "SS Aurania",
"wreck": "SS Aurania",
"r": "Sound of Mull (Lochaline)",
"lat": 56.602,
"lon": -6.325,
"td": "slack",
"hwi": 1.0,
"nd": false,
"type": "Cunard liner / WWI troopship (torpedoed 1918)",
"year": "1918",
"length": 158,
"minD": 9,
"maxD": 26,
"gas": "EAN28–32",
"lvl": "Advanced (exposed)",
"temp": "7–15",
"best": "Apr–Oct",
"curr": "Medium",
"enter": "Slack; beware heavy swell & overfalls off Caliach Point",
"tidal": "Slack water; very exposed to swell – settled weather only",
"viz": "5–15m (good but swell-dependent)",
"prot": "Not protected (heavily salvaged)",
"access": "Hard boat from Lochaline / Tobermory / Oban",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈380",
"fill": "Lochaline Dive Centre (air, nitrox); charter compressor",
"fillsite": "≈14",
"notes": "Torpedoed by UB-67 off Donegal 1918, drifted & wrecked at Caliach Point, NW Mull. Now a broken 'rummage' dive over a wide area – huge boilers stand 6–7m proud, you can swim between them. Site of the famous recovered Cunard silver."
},
{
"slug": "glen-strathallan",
"n": "Glen Strathallan",
"wreck": "Glen Strathallan",
"r": "Plymouth Sound",
"lat": 50.345,
"lon": -4.13,
"td": "none",
"hwi": 5.5,
"nd": false,
"type": "Steam yacht (scuttled 1970)",
"year": "1970",
"length": 50,
"minD": 10,
"maxD": 15,
"gas": "Air / EAN32",
"lvl": "Recreational (training)",
"temp": "8–17",
"best": "May–Oct",
"curr": "Low",
"enter": "Any state (sheltered Sound)",
"tidal": "Diveable most states; sheltered",
"viz": "2–8m",
"prot": "Not protected",
"access": "Hard boat, Plymouth Sound",
"chamber": "DDRC Healthcare, Plymouth",
"halifax": "≈335",
"fill": "In Deep / Aquanauts, Plymouth",
"fillsite": "≈3",
"notes": "Deliberately scuttled 1970 for divers; broken up but boiler & triple-expansion engine stand proud. A classic Plymouth training wreck (its engine is preserved in the Science Museum)."
},
{
"slug": "ss-wallachia",
"n": "SS Wallachia",
"wreck": "SS Wallachia",
"r": "Firth of Clyde",
"lat": 55.862,
"lon": -4.953,
"td": "slack",
"hwi": 2.0,
"nd": false,
"type": "Steamer (collision 1895)",
"year": "1895",
"length": 77,
"minD": 30,
"maxD": 34,
"gas": "EAN28–32",
"lvl": "Advanced (deep)",
"temp": "7–14",
"best": "Apr–Oct",
"curr": "Medium",
"enter": "Diveable most states; unpredictable currents – good boat cover essential",
"tidal": "Unpredictable currents; near the Wemyss Bay–Rothesay ferry route",
"viz": "3–8m (silty, can go dark)",
"prot": "Not protected",
"access": "Hard boat from Dunoon (Holy Loch) / Inverkip",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈250",
"fill": "Wreckspeditions, Dunoon (air 232/300 bar, nitrox 32%)",
"fillsite": "≈8",
"notes": "Sank 1895 after a collision; lost for 80 years, rediscovered 1977. Upright on mud at 34m, forecastle enterable. Famous for its cargo of bottled beer & earthenware. Fly a clear 'A' flag – busy shipping channel."
},
{
"slug": "mv-akka",
"n": "MV Akka",
"wreck": "MV Akka",
"r": "Firth of Clyde",
"lat": 55.942,
"lon": -4.918,
"td": "essential",
"hwi": 2.0,
"nd": false,
"type": "Swedish cargo ship (sank 1956 on the Gantocks)",
"year": "1956",
"length": 122,
"minD": 12,
"maxD": 35,
"gas": "EAN32",
"lvl": "Advanced (deep)",
"temp": "7–14",
"best": "Apr–Oct",
"curr": "Strong",
"enter": "Slack water (~1 hr either side of HW/LW Greenock)",
"tidal": "Slack water essential; lies across a slope on the Gantock rocks",
"viz": "3–10m",
"prot": "Not protected",
"access": "Hard boat from Dunoon (Holy Loch) / Inverkip",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈250",
"fill": "Wreckspeditions, Dunoon (air, nitrox 32%)",
"fillsite": "≈4",
"notes": "Struck the Gantocks off Dunoon & sank April 1956. The Clyde's most popular wreck – on her side down a slope from ~12m to ~35m with holds and structure to explore. Slack water only."
},
{
"slug": "ss-kintyre",
"n": "SS Kintyre",
"wreck": "SS Kintyre",
"r": "Firth of Clyde",
"lat": 55.87,
"lon": -4.9,
"td": "essential",
"hwi": 2.0,
"nd": false,
"type": "Coastal steamer (collision 1907)",
"year": "1907",
"length": 64,
"minD": 40,
"maxD": 48,
"gas": "Trimix (e.g. 25/25)",
"lvl": "Technical (40m+)",
"temp": "7–14",
"best": "Apr–Oct",
"curr": "Strong",
"enter": "Slack water (~1 hr either side of HW/LW Greenock)",
"tidal": "Slack water essential; deep & often dark",
"viz": "3–8m",
"prot": "Not protected",
"access": "Hard boat from Dunoon (Holy Loch) / Inverkip",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈250",
"fill": "Wreckspeditions, Dunoon (air, nitrox 32%); no helium locally – pre-arrange trimix",
"fillsite": "≈8",
"notes": "Sunk in a collision off Skelmorlie 1907. Sits upright & largely intact at ~48m – a classic Clyde technical wreck. Deep, dark and current-swept: slack water + decompression training required."
}
];

// ---------------- shared config ----------------
const TIDETIME={
 "Scapa Flow, Orkney":"stromness","Farne Islands, Northumberland":"seahouses","St Abbs & Eyemouth":"eyemouth",
 "Whitby, North Yorkshire":"whitby","Anglesey, North Wales":"holyhead","Whitsand Bay / Plymouth":"plymouth",
 "Portland & Weymouth, Dorset":"portland","Oban, Argyll":"oban","Sound of Mull (Lochaline)":"oban",
 "Plymouth Sound":"plymouth","Firth of Clyde":"greenock"};
const LAB=["GO","CAUTION","NO-GO"],CLS=["go","cau","no"];
const VCOL=["#22e39a","#ffcf4d","#ff5d6c"];
function esc(x){return String(x==null?"":x).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
function tideURL(r){return "https://www.tidetime.org/europe/united-kingdom/"+(TIDETIME[r]||"all")+".htm";}
function yrURL(s){return "https://www.yr.no/en/forecast/daily-table/"+s.lat+","+s.lon;}
function infoURL(s){var area=s.r.split(/[,(]/)[0].trim();return "https://www.google.com/search?q="+encodeURIComponent(s.n+" wreck "+area);}
function wreckURL(s){return "wreck.html?id="+s.slug;}
// ---------------- units ----------------
function getU(k,d){try{return localStorage.getItem(k)||d;}catch(e){return d;}}
function setU(k,v){try{localStorage.setItem(k,v);}catch(e){}}
function windU(){return getU("u_wind","kn");}
function waveU(){return getU("u_wave","m");}
function fmtWind(kn){if(kn==null)return "—";return windU()==="mph"?Math.round(kn*1.15078):kn;}
function fmtWave(m){if(m==null)return null;return waveU()==="ft"?(m*3.28084):m;}
function waveTxt(m){var v=fmtWave(m);return v==null?null:v.toFixed(waveU()==="ft"?1:1)+" "+waveU();}
// ---------------- astronomy / tide ----------------
const D2R=Math.PI/180;
function n360(x){x%=360;return x<0?x+360:x;}
function jdc(dt){return dt.getTime()/86400000+2440587.5-2451545.0;}
function moonRA(d){var L=n360(218.316+13.176396*d),M=(134.963+13.064993*d)*D2R,F=(93.272+13.229350*d)*D2R;
 var lon=(L+6.289*Math.sin(M))*D2R,lat=(5.128*Math.sin(F))*D2R,e=23.4397*D2R;
 return n360(Math.atan2(Math.sin(lon)*Math.cos(e)-Math.tan(lat)*Math.sin(e),Math.cos(lon))*180/Math.PI);}
function gmst(d){return n360(280.46061837+360.98564736629*d);}
function springFactor(dt){var d=jdc(dt);var De=n360(297.850+12.190749*d)*D2R;return Math.abs(Math.cos(De));}
function springLabel(dt){var sf=springFactor(dt);return sf>0.6?"Springs":sf<0.4?"Neaps":"Mid-range";}
function fmtDur(h){if(h<0)h+=12.4206;var m=Math.round(h*60);return m>=60?Math.floor(m/60)+"h "+(m%60)+"m":m+"m";}
function tidePhase(dt,lonEast,hwi){var d=jdc(dt),ra=moonRA(d),lst=n360(gmst(d)+lonEast);var H=n360(lst-ra);
 var hT=(H%180)/14.492;var hHW=((hT-hwi)%12.4206+12.4206)%12.4206;var x=hHW;if(x>6.2103)x-=12.4206;
 var ax=Math.abs(x);var nHW=12.4206-hHW;var nLW=6.2103-hHW;if(nLW<0)nLW+=12.4206;var toS=Math.min(nHW,nLW);
 var ph=(ax<1||Math.abs(ax-6.2103)<1)?"Slack":(x>0?"Ebbing":"Flooding");return {phase:ph,toSlack:toS};}
// ---------------- verdict / outlook ----------------
function verdict(gust,wave){var w=gust<=16?0:gust<=24?1:2;var s=(wave==null)?0:(wave<=0.8?0:(wave<=1.3?1:2));return Math.max(w,s);}
function outlook(fi,mi,curtime){
 if(!fi||!fi.hourly||!fi.hourly.time)return null;
 var ft=fi.hourly.time,fg=fi.hourly.wind_gusts_10m,key=curtime.slice(0,13);
 var idx=ft.findIndex(function(t){return t.slice(0,13)===key;});if(idx<0)idx=ft.findIndex(function(t){return t>=curtime;});if(idx<0)idx=0;
 var mt=(mi&&mi.hourly&&mi.hourly.time)?mi.hourly.time:null;var mw=(mi&&mi.hourly)?mi.hourly.wave_height:null;
 var midx=-1;if(mt){midx=mt.findIndex(function(t){return t.slice(0,13)===key;});if(midx<0)midx=mt.findIndex(function(t){return t>=curtime;});}
 var hrs=[];for(var h=0;h<12;h++){var gi=idx+h;if(gi>=ft.length)break;
  var gust=(fg[gi]!=null)?Math.round(fg[gi]):null;var wave=null;if(mt&&midx>=0&&(midx+h)<mw.length&&mw[midx+h]!=null)wave=mw[midx+h];
  var v=(gust==null)?3:verdict(gust,wave);hrs.push({t:ft[gi].slice(11,16),gust:gust,wave:wave,v:v});}
 return hrs;}
function computeConditions(s,Fi,Mi,now){
 var cur=(Fi&&Fi.current)?Fi.current:null,mar=(Mi&&Mi.current)?Mi.current:null;
 var gustKn=cur?Math.round(cur.wind_gusts_10m):null,windKn=cur?Math.round(cur.wind_speed_10m):null;
 var wave=(mar&&mar.wave_height!=null)?mar.wave_height:null;var hrs=cur?outlook(Fi,Mi,cur.time):null;
 var v,cls,lab,tideMain,tideSub,tcls;
 if(s.nd){v=-1;cls="nd";lab="NO DIVE";tideMain="—";tideSub="";tcls="";}
 else if(gustKn==null){v=3;cls="no";lab="—";tideMain="—";tideSub="";tcls="";}
 else{v=verdict(gustKn,wave);
  if(s.td==="none"){tideMain="Any state";tcls="ok";tideSub="";}
  else{var tp=tidePhase(now,s.lon,s.hwi);v=Math.max(v,1);tcls="slack";
   tideMain=(s.td==="essential"?"Slack essential":"Slack advised");tideSub=tp.phase+" · slack ~"+fmtDur(tp.toSlack)+" (est)";}
  cls=CLS[v];lab=LAB[v];}
 var sr=null,ss=null;if(Fi&&Fi.daily&&Fi.daily.sunrise){sr=Fi.daily.sunrise[0];ss=Fi.daily.sunset[0];}
 return {gustKn:gustKn,windKn:windKn,wave:wave,hrs:hrs,v:v,cls:cls,lab:lab,tideMain:tideMain,tideSub:tideSub,tcls:tcls,sunrise:sr,sunset:ss};
}
function hhmm(iso){if(!iso)return "—";return iso.slice(11,16);}
// ---------------- fetch ----------------
function asArr(d){return Array.isArray(d)?d:[d];}
function fetchJSON(u){return fetch(u).then(function(r){if(!r.ok)throw new Error("HTTP "+r.status);return r.json();});}
function fetchAll(days,subset){
 days=days||2;var list=subset||SITES;
 var lats=list.map(function(s){return s.lat;}).join(","),lons=list.map(function(s){return s.lon;}).join(",");
 var fUrl="https://api.open-meteo.com/v1/forecast?latitude="+lats+"&longitude="+lons+"&current=wind_speed_10m,wind_gusts_10m,weather_code&hourly=wind_speed_10m,wind_gusts_10m&daily=sunrise,sunset,wind_gusts_10m_max&wind_speed_unit=kn&forecast_days="+days+"&timezone=auto";
 var mUrl="https://marine-api.open-meteo.com/v1/marine?latitude="+lats+"&longitude="+lons+"&current=wave_height,swell_wave_height&hourly=wave_height&daily=wave_height_max&forecast_days="+days+"&timezone=auto";
 return Promise.allSettled([fetchJSON(fUrl),fetchJSON(mUrl)]).then(function(res){
  if(res[0].status!=="fulfilled")throw res[0].reason;
  var F=asArr(res[0].value),M=(res[1].status==="fulfilled")?asArr(res[1].value):[];
  return {F:F,M:M,now:new Date()};});
}
