// AUTO-GENERATED from UK_Wreck_Dives_Database.xlsx — shared data + helpers
const SITES=[
{
"slug": "sms-markgraf",
"n": "SMS Markgraf",
"wreck": "SMS Markgraf",
"r": "Scapa Flow, Orkney",
"lat": 58.872,
"lon": -3.17,
"td": "none",
"hwi": 8.0,
"nd": false,
"type": "German WWI battleship (König class)",
"year": "1919 (scuttled)",
"length": 175,
"minD": 24,
"maxD": 45,
"gas": "Trimix (e.g. 21/35)",
"lvl": "Technical (40m+)",
"temp": "6–14",
"best": "May (viz) & Sep–Oct",
"curr": "Low",
"enter": "Any state – sheltered",
"tidal": "No tidal constraints on the German Fleet",
"viz": "6–15m",
"prot": "Scheduled Monument; within Scapa Flow Historic MPA (Nov 2025) – no removal",
"access": "Hard boat / liveaboard from Stromness",
"chamber": "Orkney Hyperbaric Trust, Stromness (24/7)",
"halifax": "≈475 to Scrabster + ferry",
"fill": "Scapa Scuba, Stromness / onboard charter (air, nitrox, trimix)",
"fillsite": "≈8 (steam)",
"notes": "Deepest & most intact of the 3 battleships; headline features (casemates, rangefinders) sit deep. On her starboard side."
},
{
"slug": "sms-kronprinz-wilhelm",
"n": "SMS Kronprinz Wilhelm",
"wreck": "SMS Kronprinz Wilhelm",
"r": "Scapa Flow, Orkney",
"lat": 58.876,
"lon": -3.171,
"td": "none",
"hwi": 8.0,
"nd": false,
"type": "German WWI battleship (König class)",
"year": "1919 (scuttled)",
"length": 175,
"minD": 12,
"maxD": 38,
"gas": "EAN28 / Trimix",
"lvl": "Advanced–Technical",
"temp": "6–14",
"best": "May (viz) & Sep–Oct",
"curr": "Low",
"enter": "Any state – sheltered",
"tidal": "No tidal constraints",
"viz": "6–15m",
"prot": "Scheduled Monument; within Scapa Flow Historic MPA – no removal",
"access": "Hard boat / liveaboard from Stromness",
"chamber": "Orkney Hyperbaric Trust, Stromness (24/7)",
"halifax": "≈475 to Scrabster + ferry",
"fill": "Scapa Scuba, Stromness / onboard charter",
"fillsite": "≈8 (steam)",
"notes": "Most accessible battleship – inverted, bilge keel/port side rises to ~12m. 'Shake hands with a battleship at 15m.'"
},
{
"slug": "sms-coln",
"n": "SMS Cöln",
"wreck": "SMS Cöln",
"r": "Scapa Flow, Orkney",
"lat": 58.884,
"lon": -3.155,
"td": "none",
"hwi": 8.0,
"nd": false,
"type": "German WWI light cruiser",
"year": "1919 (scuttled)",
"length": 155,
"minD": 22,
"maxD": 36,
"gas": "EAN28",
"lvl": "Advanced (deep)",
"temp": "6–14",
"best": "May (viz) & Sep–Oct",
"curr": "Low",
"enter": "Any state – sheltered",
"tidal": "No tidal constraints",
"viz": "6–15m",
"prot": "Scheduled Monument; within Scapa Flow Historic MPA – no removal",
"access": "Hard boat / liveaboard from Stromness",
"chamber": "Orkney Hyperbaric Trust, Stromness (24/7)",
"halifax": "≈475 to Scrabster + ferry",
"fill": "Scapa Scuba, Stromness / onboard charter",
"fillsite": "≈8 (steam)",
"notes": "Most intact of the four cruisers; long swim along an unbroken hull. On starboard side."
},
{
"slug": "sms-karlsruhe",
"n": "SMS Karlsruhe",
"wreck": "SMS Karlsruhe",
"r": "Scapa Flow, Orkney",
"lat": 58.885,
"lon": -3.198,
"td": "none",
"hwi": 8.0,
"nd": false,
"type": "German WWI light cruiser",
"year": "1919 (scuttled)",
"length": 150,
"minD": 14,
"maxD": 27,
"gas": "EAN32",
"lvl": "Recreational (AOW+)",
"temp": "6–14",
"best": "May (viz) & Sep–Oct",
"curr": "Low",
"enter": "Any state – sheltered",
"tidal": "No tidal constraints",
"viz": "6–15m",
"prot": "Scheduled Monument; within Scapa Flow Historic MPA – no removal",
"access": "Hard boat / liveaboard from Stromness",
"chamber": "Orkney Hyperbaric Trust, Stromness (24/7)",
"halifax": "≈475 to Scrabster + ferry",
"fill": "Scapa Scuba, Stromness / onboard charter",
"fillsite": "≈8 (steam)",
"notes": "Shallowest cruiser; heavily broken so the most marine-life rich – a good first Scapa wreck."
},
{
"slug": "sms-brummer",
"n": "SMS Brummer",
"wreck": "SMS Brummer",
"r": "Scapa Flow, Orkney",
"lat": 58.884,
"lon": -3.152,
"td": "none",
"hwi": 8.0,
"nd": false,
"type": "German WWI mine-laying cruiser",
"year": "1919 (scuttled)",
"length": 140,
"minD": 22,
"maxD": 36,
"gas": "EAN28",
"lvl": "Advanced (deep)",
"temp": "6–14",
"best": "May (viz) & Sep–Oct",
"curr": "Low",
"enter": "Any state – sheltered",
"tidal": "No tidal constraints",
"viz": "6–15m",
"prot": "Scheduled Monument; within Scapa Flow Historic MPA – no removal",
"access": "Hard boat / liveaboard from Stromness",
"chamber": "Orkney Hyperbaric Trust, Stromness (24/7)",
"halifax": "≈475 to Scrabster + ferry",
"fill": "Scapa Scuba, Stromness / onboard charter",
"fillsite": "≈8 (steam)",
"notes": "Often rated the single best dive in the Flow – intact bow, vivid life. On starboard side; deck sections peeling (deteriorating)."
},
{
"slug": "hms-royal-oak",
"n": "HMS Royal Oak",
"wreck": "HMS Royal Oak",
"r": "Scapa Flow, Orkney",
"lat": 58.931,
"lon": -2.984,
"td": "nd",
"hwi": 0,
"nd": true,
"type": "Royal Navy battleship (Revenge class)",
"year": "1939",
"length": "189",
"minD": "–",
"maxD": 33,
"gas": "N/A – diving prohibited",
"lvl": "N/A",
"temp": "6–14",
"best": "N/A",
"curr": "Low",
"enter": "N/A",
"tidal": "N/A",
"viz": "–",
"prot": "CONTROLLED SITE (Protection of Military Remains Act) – ALL diving banned. War grave (~835 lost).",
"access": "None – marked by memorial buoy",
"chamber": "Orkney Hyperbaric Trust, Stromness",
"halifax": "≈475 to Scrabster + ferry",
"fill": "N/A",
"fillsite": "N/A",
"notes": "Listed as a WARNING: torpedoed by U-47, 14 Oct 1939. Highest PMRA protection – diving/interference is a criminal offence. Still leaks oil."
},
{
"slug": "ss-somali",
"n": "SS Somali",
"wreck": "SS Somali",
"r": "Farne Islands, Northumberland",
"lat": 55.553,
"lon": -1.607,
"td": "slack",
"hwi": 3.5,
"nd": false,
"type": "Passenger-cargo steamer (WWII bomb casualty)",
"year": "1941",
"length": 137,
"minD": 20,
"maxD": 30,
"gas": "EAN28–32",
"lvl": "Advanced (deep)",
"temp": "6–15",
"best": "May–Oct (viz best Jun–Sep)",
"curr": "Medium",
"enter": "Slack advisable",
"tidal": "Some tidal movement; slack advisable",
"viz": "up to 20m (among UK's clearest)",
"prot": "Privately owned wreck (not designated)",
"access": "Hard boat from Seahouses",
"chamber": "Via 999 / Coastguard (BHA duty chamber)",
"halifax": "≈150",
"fill": "Sovereign Diving, Seahouses (air, nitrox)",
"fillsite": "≈4",
"notes": "Bombed off Blyth 1941; burned & broke up off Beadnell Point. Big boilers, engine, 12-pdr AA gun. Salvaged over years but takes several dives."
},
{
"slug": "chris-christensen",
"n": "Chris Christensen",
"wreck": "Chris Christensen",
"r": "Farne Islands, Northumberland",
"lat": 55.639,
"lon": -1.604,
"td": "essential",
"hwi": 3.5,
"nd": false,
"type": "Danish steamship (grounded 1915)",
"year": "1915",
"length": "~90",
"minD": 20,
"maxD": 33,
"gas": "EAN28",
"lvl": "Advanced (deep)",
"temp": "6–15",
"best": "May–Oct (viz best Jun–Sep)",
"curr": "Strong",
"enter": "Slack essential (≈2h after LW Seahouses)",
"tidal": "Slack essential; strong tides, downcurrents reported",
"viz": "up to 20m",
"prot": "Not protected",
"access": "Hard boat from Seahouses",
"chamber": "Via 999 / Coastguard (BHA duty chamber)",
"halifax": "≈150",
"fill": "Sovereign Diving, Seahouses (air, nitrox)",
"fillsite": "≈5",
"notes": "Aground on Longstone Ends 1915. Broken but scenic – boilers, engine, girders, iron steering wheel. Sloping reef eases the ascent. Conger, wolffish, ling."
},
{
"slug": "ss-glanmire",
"n": "SS Glanmire",
"wreck": "SS Glanmire",
"r": "St Abbs & Eyemouth, Berwickshire",
"lat": 55.902,
"lon": -2.132,
"td": "slack",
"hwi": 3.5,
"nd": false,
"type": "Steamship (sank 1912)",
"year": "1912",
"length": "~85",
"minD": 20,
"maxD": 30,
"gas": "EAN28–32",
"lvl": "Advanced (deep)",
"temp": "6–14",
"best": "Jun–Sep",
"curr": "Low–Medium",
"enter": "Slack water",
"tidal": "Slack water; 300m offshore, sheltered",
"viz": "5–15m",
"prot": "Within Berwickshire Marine Reserve – no removal of marine life",
"access": "Hard boat from Eyemouth",
"chamber": "Via 999 / Coastguard",
"halifax": "≈172",
"fill": "Marine Quest / The Harbourside, Eyemouth (air, nitrox, trimix)",
"fillsite": "≈5",
"notes": "One of the area's best – wolffish, conger, big fish shoals. NB deeper local tech wrecks (HMS Pathfinder ~68m, U-12) are war graves – respect, no penetration/removal."
},
{
"slug": "hmhs-rohilla",
"n": "HMHS Rohilla",
"wreck": "HMHS Rohilla",
"r": "Whitby, North Yorkshire",
"lat": 54.4996,
"lon": -0.5893,
"td": "none",
"hwi": 3.5,
"nd": false,
"type": "Hospital ship (wrecked in storm 1914)",
"year": "1914",
"length": 140,
"minD": 6,
"maxD": 16,
"gas": "Air / EAN32",
"lvl": "Recreational (all levels)",
"temp": "6–16",
"best": "Jun–Sep (after a dry spell)",
"curr": "Low",
"enter": "Any state (avoid spring tides)",
"tidal": "Small tidal range – diveable most states; avoid springs",
"viz": "2–8m (poor after rain – Esk runoff)",
"prot": "Local syndicate – no recovery by custom",
"access": "RIB / club boat from Whitby harbour slipway",
"chamber": "Via 999 / Coastguard",
"halifax": "≈62",
"fill": "No public fill in Whitby – fill at Academy Divers, Halifax (air/nitrox/trimix) before travel, or use a club compressor",
"fillsite": "≈62 (fill inland)",
"notes": "Grounded on Whitby Rock 30 Oct 1914; ~85 lives lost. Shallow & scattered – 4 boilers, shaft. Great training / off-gassing dive right by the harbour."
},
{
"slug": "uc-70",
"n": "UC-70",
"wreck": "UC-70",
"r": "Whitby, North Yorkshire",
"lat": 54.527,
"lon": -0.669,
"td": "essential",
"hwi": 3.5,
"nd": false,
"type": "German WWI minelaying U-boat (UC-II)",
"year": "1918",
"length": "~50",
"minD": 22,
"maxD": 24,
"gas": "EAN32",
"lvl": "Advanced",
"temp": "6–16",
"best": "Jun–Sep (after a dry spell)",
"curr": "Strong",
"enter": "Slack only (≈2h after HW/LW Whitby)",
"tidal": "Slack essential; strong tides",
"viz": "2–8m",
"prot": "Sunk 1918 – not a designated war grave, but treat with respect",
"access": "RIB / club boat from Whitby (~3 mi up coast)",
"chamber": "Via 999 / Coastguard",
"halifax": "≈62",
"fill": "As Rohilla – fill at Academy Divers, Halifax before travel",
"fillsite": "≈62 (fill inland)",
"notes": "Depth-charged/rammed 1918. Sits near-upright with slight port list; deck gun intact & pointing up, open hatches. No heavy deco – a good step toward deeper wrecks."
},
{
"slug": "the-kimya",
"n": "The Kimya",
"wreck": "MV Kimya",
"r": "Anglesey, North Wales",
"lat": 53.159,
"lon": -4.449,
"td": "none",
"hwi": 9.0,
"nd": false,
"type": "Steel tanker (capsized 1991)",
"year": "1991",
"length": 73,
"minD": 6,
"maxD": 15,
"gas": "Air / EAN32",
"lvl": "Recreational (novice-friendly)",
"temp": "8–16",
"best": "Apr–Oct",
"curr": "Low",
"enter": "Any state (little current)",
"tidal": "Diveable all states of tide",
"viz": "3–10m",
"prot": "Not protected",
"access": "RIB from Trearddur Bay / Holyhead",
"chamber": "Via 999 / Coastguard",
"halifax": "≈135",
"fill": "Anglesey Divers, Holyhead (air 300 bar, nitrox)",
"fillsite": "≈10",
"notes": "Sank 16 mi SW of Holyhead 1991 (sunflower-oil cargo); salvaged & re-sunk on sand. Rudder stands 7m. Ideal season-opener / training wreck, upright."
},
{
"slug": "ss-missouri",
"n": "SS Missouri",
"wreck": "SS Missouri",
"r": "Anglesey, North Wales",
"lat": 53.32,
"lon": -4.7,
"td": "slack",
"hwi": 9.0,
"nd": false,
"type": "Steamship (ran aground 1886)",
"year": "1886",
"length": 130,
"minD": 5,
"maxD": 15,
"gas": "Air / EAN32",
"lvl": "Recreational",
"temp": "8–16",
"best": "Apr–Oct",
"curr": "Medium",
"enter": "Slack advisable (near North Stack tide race)",
"tidal": "Slack advisable; broken & shallow",
"viz": "3–10m",
"prot": "Not protected",
"access": "RIB from Trearddur Bay (~15 min)",
"chamber": "Via 999 / Coastguard",
"halifax": "≈135",
"fill": "Anglesey Divers, Holyhead (air, nitrox)",
"fillsite": "≈4",
"notes": "Aground near North Stack 1886. Broken & shallow but scenic with lots of life; within a 15-min RIB ride of Trearddur Bay."
},
{
"slug": "james-eagan-layne",
"n": "James Eagan Layne",
"wreck": "James Eagan Layne",
"r": "Whitsand Bay / Plymouth",
"lat": 50.3268,
"lon": -4.2453,
"td": "none",
"hwi": 5.5,
"nd": false,
"type": "US WWII Liberty ship (torpedoed 1945)",
"year": "1945",
"length": 130,
"minD": 8,
"maxD": 24,
"gas": "EAN32",
"lvl": "Recreational (AOW+)",
"temp": "8–17",
"best": "May–Oct",
"curr": "Low",
"enter": "Any state of tide",
"tidal": "Diveable any state",
"viz": "3–10m",
"prot": "War casualty but not designated",
"access": "Hard boat from Plymouth (Mount Batten / Queen Anne's Battery)",
"chamber": "DDRC Healthcare, Plymouth",
"halifax": "≈335",
"fill": "In Deep Dive Centre or Aquanauts, Plymouth (air, nitrox, trimix)",
"fillsite": "≈7",
"notes": "Torpedoed by U-1195, 21 Mar 1945; sank upright in Whitsand Bay. Bow ~8m, holds accessible. UK's most famous Liberty ship – ideal wreck-spec dive."
},
{
"slug": "hms-scylla",
"n": "HMS Scylla",
"wreck": "HMS Scylla",
"r": "Whitsand Bay / Plymouth",
"lat": 50.335,
"lon": -4.246,
"td": "none",
"hwi": 5.5,
"nd": false,
"type": "RN Leander frigate (scuttled as reef 2004)",
"year": "2004",
"length": 113,
"minD": 9,
"maxD": 24,
"gas": "EAN32",
"lvl": "Recreational (AOW+)",
"temp": "8–17",
"best": "May–Oct",
"curr": "Low–Medium",
"enter": "Not slack-free; avoid springs & busy weekends",
"tidal": "Some tide; visibility silts with diver traffic",
"viz": "3–10m",
"prot": "No penetration permitted (unsafe since 2014) – NMA guidance",
"access": "Hard boat from Plymouth",
"chamber": "DDRC Healthcare, Plymouth",
"halifax": "≈335",
"fill": "In Deep / Aquanauts, Plymouth",
"fillsite": "≈7",
"notes": "Europe's first artificial reef, sunk 27 Mar 2004; 250+ species recorded. Multi-level – superb for training & photography. Do NOT penetrate the interior."
},
{
"slug": "countess-of-erne",
"n": "Countess of Erne",
"wreck": "Countess of Erne",
"r": "Portland & Weymouth, Dorset",
"lat": 50.573,
"lon": -2.43,
"td": "none",
"hwi": 6.5,
"nd": false,
"type": "Iron paddle steamer / coal hulk",
"year": "1935",
"length": 74,
"minD": 7,
"maxD": 15,
"gas": "Air / EAN32",
"lvl": "Recreational (novice/training)",
"temp": "8–18",
"best": "May–Oct",
"curr": "Low (gentle)",
"enter": "Any state (sheltered in harbour)",
"tidal": "Diveable all states; sheltered by breakwater",
"viz": "3–8m (silty)",
"prot": "Not protected",
"access": "Hard boat from Portland Marina / free slip at Castletown (harbour permit needed)",
"chamber": "DDRC Plymouth / Poole via 999-Coastguard",
"halifax": "≈295",
"fill": "Portland Gas Shack & SkinDeeper (air, nitrox, trimix, 300 bar)",
"fillsite": "≈2",
"notes": "Broke moorings & sank against the breakwater 1935. Upright, 3 open holds (silty swim-throughs). Deteriorating & 'spiky' – carry an SMB (harbour-entrance current close by)."
},
{
"slug": "m2-submarine",
"n": "M2 Submarine",
"wreck": "HMS M2",
"r": "Portland & Weymouth, Dorset",
"lat": 50.545,
"lon": -2.56,
"td": "essential",
"hwi": 6.5,
"nd": false,
"type": "RN submarine (aircraft-carrier sub, sank 1932)",
"year": "1932",
"length": 90,
"minD": 30,
"maxD": 36,
"gas": "EAN28",
"lvl": "Advanced (deep)",
"temp": "8–17",
"best": "May–Oct",
"curr": "Medium–Strong",
"enter": "Slack water",
"tidal": "Slack water essential",
"viz": "3–10m",
"prot": "War grave (~60 lost) – dive with respect, no penetration/removal",
"access": "Hard boat from Portland / Weymouth",
"chamber": "DDRC Plymouth / Poole via Coastguard",
"halifax": "≈295",
"fill": "Portland Gas Shack & SkinDeeper",
"fillsite": "≈6",
"notes": "Sank Jan 1932, probably flooded via the open hangar (doors still open). Iconic – launched a seaplane by catapult. All hands lost; treat as a war grave."
},
{
"slug": "ss-salsette",
"n": "SS Salsette",
"wreck": "SS Salsette",
"r": "Portland & Weymouth, Dorset",
"lat": 50.52,
"lon": -2.76,
"td": "slack",
"hwi": 6.5,
"nd": false,
"type": "P&O ocean liner (torpedoed 1917)",
"year": "1917",
"length": 134,
"minD": 27,
"maxD": 45,
"gas": "Trimix (e.g. 25/25)",
"lvl": "Technical (40m+)",
"temp": "8–16",
"best": "Jun–Sep",
"curr": "Medium",
"enter": "Slack water",
"tidal": "Slack water; ~15 mi offshore in Lyme Bay",
"viz": "5–12m",
"prot": "War casualty, not designated",
"access": "Hard boat from Portland / Weymouth",
"chamber": "DDRC Plymouth / Poole via Coastguard",
"halifax": "≈295",
"fill": "Portland Gas Shack & SkinDeeper (trimix)",
"fillsite": "≈15",
"notes": "Torpedoed by UB-40, 20 Jul 1917; 15 crew lost. Intact on her side at ~45m – a classic Dorset technical wreck with fine fittings."
},
{
"slug": "aeolian-sky",
"n": "Aeolian Sky",
"wreck": "Aeolian Sky",
"r": "Portland & Weymouth, Dorset",
"lat": 50.553,
"lon": -2.352,
"td": "slack",
"hwi": 6.5,
"nd": false,
"type": "Greek cargo ship (collision 1979)",
"year": "1979",
"length": 157,
"minD": 25,
"maxD": 30,
"gas": "EAN28–32",
"lvl": "Advanced (deep)",
"temp": "8–17",
"best": "May–Oct",
"curr": "Medium",
"enter": "Slack water",
"tidal": "Slack water",
"viz": "3–10m",
"prot": "Not protected",
"access": "Hard boat from Portland / Weymouth",
"chamber": "DDRC Plymouth / Poole via Coastguard",
"halifax": "≈295",
"fill": "Portland Gas Shack & SkinDeeper",
"fillsite": "≈5",
"notes": "Sank 1979 after a collision, general cargo (incl. Land Rovers). Huge & broken but impressive – a big single dive. Silty."
},
{
"slug": "ss-breda",
"n": "SS Breda",
"wreck": "SS Breda",
"r": "Oban, Argyll",
"lat": 56.476,
"lon": -5.418,
"td": "none",
"hwi": 1.0,
"nd": false,
"type": "Dutch cargo ship (bombed 1940)",
"year": "1940",
"length": 122,
"minD": 9,
"maxD": 30,
"gas": "EAN28–32",
"lvl": "Recreational (all levels)",
"temp": "7–15",
"best": "Apr–Oct (spring best viz)",
"curr": "Low (non-tidal bay)",
"enter": "Any state (wait 2h after ebb begins after heavy rain)",
"tidal": "Effectively non-tidal in Ardmucknish Bay",
"viz": "5–15m (silt in holds)",
"prot": "Not protected",
"access": "Hard boat / RIB from Oban (Port Gallanach), Ardmucknish Bay",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈340",
"fill": "Puffin Dive Centre, Oban (air; nitrox by arrangement)",
"fillsite": "≈7",
"notes": "Bombed 1940 (near-miss); cargo incl. aircraft, vehicles, motorcycles, cement. Upright, bow ~9m to seabed ~30m – suits everyone. Superstructure wire-swept in the 60s."
},
{
"slug": "ss-thesis",
"n": "SS Thesis",
"wreck": "SS Thesis",
"r": "Oban, Argyll",
"lat": 56.499,
"lon": -5.691,
"td": "essential",
"hwi": 1.0,
"nd": false,
"type": "Iron screw steamer (ran aground 1889)",
"year": "1889",
"length": 51,
"minD": 20,
"maxD": 32,
"gas": "EAN28–32",
"lvl": "Advanced (deep, experienced)",
"temp": "7–15",
"best": "Apr–Oct",
"curr": "Strong",
"enter": "Slack – middle 4 hrs of the flooding tide",
"tidal": "Slack/flooding tide only; tide whips round Rubha an Ridire and can turn fast – experienced divers only",
"viz": "10–20m (often excellent – open hull lets light in)",
"prot": "Not protected",
"access": "Hard boat / day-boat from Oban (Sound of Mull, ~13.5 NM)",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈340",
"fill": "Puffin Dive Centre, Oban (air; nitrox by arrangement)",
"fillsite": "≈16",
"notes": "Ran aground at Inninmore Point 1889. Hull plates blasted/fallen away so you can swim the length below deck level with light pouring in – very photogenic. Often done as the 2nd dive heading back to Oban."
},
{
"slug": "ss-shuna",
"n": "SS Shuna",
"wreck": "SS Shuna",
"r": "Oban, Argyll",
"lat": 56.53,
"lon": -5.83,
"td": "none",
"hwi": 1.0,
"nd": false,
"type": "Glasgow screw steamer (wrecked 1913)",
"year": "1913",
"length": 73,
"minD": 26,
"maxD": 32,
"gas": "EAN28–32",
"lvl": "Advanced (deep)",
"temp": "7–15",
"best": "Apr–Oct",
"curr": "Low",
"enter": "Any state (currents <½ kt)",
"tidal": "Diveable all states; gentle NW/SE current",
"viz": "5–12m (silty – careful finning)",
"prot": "Not protected",
"access": "Hard boat from Oban (Sound of Mull)",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈340",
"fill": "Puffin Dive Centre, Oban (air; nitrox by arrangement)",
"fillsite": "≈21",
"notes": "Coal/iron cargo, Glasgow to Gothenburg; struck the Grey Rocks 1913. Upright and largely intact, bows pointing SE. Known as the ‘shitty Shuna’ for its silt – stay off the deck and mind your fins."
},
{
"slug": "madam-alice",
"n": "Madam Alice",
"wreck": "Madam Alice",
"r": "Oban, Argyll",
"lat": 56.452,
"lon": -5.485,
"td": "slack",
"hwi": 1.0,
"nd": false,
"type": "Steamer (lost 1918)",
"year": "1918",
"length": 46,
"minD": 32,
"maxD": 38,
"gas": "EAN28",
"lvl": "Advanced (deep)",
"temp": "7–15",
"best": "Apr–Oct",
"curr": "Low–Medium",
"enter": "Slack advisable",
"tidal": "On a gently sloping seabed; shallowest point ~32m",
"viz": "5–12m",
"prot": "Not protected",
"access": "Hard boat / RIB from Oban, Ardmucknish Bay",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈340",
"fill": "Puffin Dive Centre, Oban (air; nitrox by arrangement)",
"fillsite": "≈8",
"notes": "Fully intact ~150ft (46m) vessel lost 1918, marked by a can visible at low water (needs echo-sounding to locate). A deeper, quieter alternative to the nearby Breda. Depths approximate – confirm with Puffin/skipper."
},
{
"slug": "ss-hispania",
"n": "SS Hispania",
"wreck": "SS Hispania",
"r": "Sound of Mull (Lochaline)",
"lat": 56.582,
"lon": -5.987,
"td": "essential",
"hwi": 1.0,
"nd": false,
"type": "Swedish steamship (grounded 1954)",
"year": "1954",
"length": 72,
"minD": 15,
"maxD": 30,
"gas": "EAN28–32",
"lvl": "Advanced (deep)",
"temp": "7–15",
"best": "Apr–Oct",
"curr": "Medium–Strong",
"enter": "Slack water essential (spring HW/LW slack)",
"tidal": "Slack water essential; strong tides",
"viz": "5–15m",
"prot": "Not protected",
"access": "Hard boat from Lochaline",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈380",
"fill": "Lochaline Dive Centre (air, nitrox); charter compressor for air",
"fillsite": "≈4",
"notes": "Ran onto a reef Dec 1954; the captain went down with the ship. Upright, slight starboard list, near-intact and smothered in life – rated one of Scotland's best scenic wrecks. Decks 15–20m."
},
{
"slug": "ss-rondo",
"n": "SS Rondo",
"wreck": "SS Rondo",
"r": "Sound of Mull (Lochaline)",
"lat": 56.538,
"lon": -5.912,
"td": "essential",
"hwi": 1.0,
"nd": false,
"type": "Cargo steamer (wrecked 1935)",
"year": "1935",
"length": 80,
"minD": 8,
"maxD": 50,
"gas": "Trimix (deep) / EAN32 (shallow)",
"lvl": "Advanced–Technical",
"temp": "7–15",
"best": "Apr–Oct",
"curr": "Strong",
"enter": "Slack or ebb",
"tidal": "Slack/ebb; strong currents on the wreck",
"viz": "5–15m (can be gin-clear)",
"prot": "Not protected",
"access": "Hard boat from Lochaline",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈380",
"fill": "Lochaline Dive Centre (air, nitrox); charter compressor",
"fillsite": "≈3",
"notes": "Sits almost vertical – rudder near surface (~6–10m), bow ~50m. 'Three dives in one': deep wreck + reef + off-gas on ascent. History of accidents – respect the current."
},
{
"slug": "ss-aurania",
"n": "SS Aurania",
"wreck": "SS Aurania",
"r": "Sound of Mull (Lochaline)",
"lat": 56.602,
"lon": -6.325,
"td": "slack",
"hwi": 1.0,
"nd": false,
"type": "Cunard liner / WWI troopship (torpedoed 1918)",
"year": "1918",
"length": 158,
"minD": 9,
"maxD": 26,
"gas": "EAN28–32",
"lvl": "Advanced (exposed)",
"temp": "7–15",
"best": "Apr–Oct",
"curr": "Medium",
"enter": "Slack; beware heavy swell & overfalls off Caliach Point",
"tidal": "Slack water; very exposed to swell – settled weather only",
"viz": "5–15m (good but swell-dependent)",
"prot": "Not protected (heavily salvaged)",
"access": "Hard boat from Lochaline / Tobermory / Oban",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈380",
"fill": "Lochaline Dive Centre (air, nitrox); charter compressor",
"fillsite": "≈14",
"notes": "Torpedoed by UB-67 off Donegal 1918, drifted & wrecked at Caliach Point, NW Mull. Now a broken 'rummage' dive over a wide area – huge boilers stand 6–7m proud, you can swim between them. Site of the famous recovered Cunard silver."
},
{
"slug": "glen-strathallan",
"n": "Glen Strathallan",
"wreck": "Glen Strathallan",
"r": "Plymouth Sound",
"lat": 50.345,
"lon": -4.13,
"td": "none",
"hwi": 5.5,
"nd": false,
"type": "Steam yacht (scuttled 1970)",
"year": "1970",
"length": 50,
"minD": 10,
"maxD": 15,
"gas": "Air / EAN32",
"lvl": "Recreational (training)",
"temp": "8–17",
"best": "May–Oct",
"curr": "Low",
"enter": "Any state (sheltered Sound)",
"tidal": "Diveable most states; sheltered",
"viz": "2–8m",
"prot": "Not protected",
"access": "Hard boat, Plymouth Sound",
"chamber": "DDRC Healthcare, Plymouth",
"halifax": "≈335",
"fill": "In Deep / Aquanauts, Plymouth",
"fillsite": "≈3",
"notes": "Deliberately scuttled 1970 for divers; broken up but boiler & triple-expansion engine stand proud. A classic Plymouth training wreck (its engine is preserved in the Science Museum)."
},
{
"slug": "ss-wallachia",
"n": "SS Wallachia",
"wreck": "SS Wallachia",
"r": "Firth of Clyde",
"lat": 55.862,
"lon": -4.953,
"td": "slack",
"hwi": 2.0,
"nd": false,
"type": "Steamer (collision 1895)",
"year": "1895",
"length": 77,
"minD": 30,
"maxD": 34,
"gas": "EAN28–32",
"lvl": "Advanced (deep)",
"temp": "7–14",
"best": "Apr–Oct",
"curr": "Medium",
"enter": "Diveable most states; unpredictable currents – good boat cover essential",
"tidal": "Unpredictable currents; near the Wemyss Bay–Rothesay ferry route",
"viz": "3–8m (silty, can go dark)",
"prot": "Not protected",
"access": "Hard boat from Dunoon (Holy Loch) / Inverkip",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈250",
"fill": "Wreckspeditions, Dunoon (air 232/300 bar, nitrox 32%)",
"fillsite": "≈8",
"notes": "Sank 1895 after a collision; lost for 80 years, rediscovered 1977. Upright on mud at 34m, forecastle enterable. Famous for its cargo of bottled beer & earthenware. Fly a clear 'A' flag – busy shipping channel."
},
{
"slug": "mv-akka",
"n": "MV Akka",
"wreck": "MV Akka",
"r": "Firth of Clyde",
"lat": 55.942,
"lon": -4.918,
"td": "essential",
"hwi": 2.0,
"nd": false,
"type": "Swedish cargo ship (sank 1956 on the Gantocks)",
"year": "1956",
"length": 122,
"minD": 12,
"maxD": 35,
"gas": "EAN32",
"lvl": "Advanced (deep)",
"temp": "7–14",
"best": "Apr–Oct",
"curr": "Strong",
"enter": "Slack water (~1 hr either side of HW/LW Greenock)",
"tidal": "Slack water essential; lies across a slope on the Gantock rocks",
"viz": "3–10m",
"prot": "Not protected",
"access": "Hard boat from Dunoon (Holy Loch) / Inverkip",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈250",
"fill": "Wreckspeditions, Dunoon (air, nitrox 32%)",
"fillsite": "≈4",
"notes": "Struck the Gantocks off Dunoon & sank April 1956. The Clyde's most popular wreck – on her side down a slope from ~12m to ~35m with holds and structure to explore. Slack water only."
},
{
"slug": "ss-kintyre",
"n": "SS Kintyre",
"wreck": "SS Kintyre",
"r": "Firth of Clyde",
"lat": 55.87,
"lon": -4.9,
"td": "essential",
"hwi": 2.0,
"nd": false,
"type": "Coastal steamer (collision 1907)",
"year": "1907",
"length": 64,
"minD": 40,
"maxD": 48,
"gas": "Trimix (e.g. 25/25)",
"lvl": "Technical (40m+)",
"temp": "7–14",
"best": "Apr–Oct",
"curr": "Strong",
"enter": "Slack water (~1 hr either side of HW/LW Greenock)",
"tidal": "Slack water essential; deep & often dark",
"viz": "3–8m",
"prot": "Not protected",
"access": "Hard boat from Dunoon (Holy Loch) / Inverkip",
"chamber": "Via 999 / Coastguard (Scottish network)",
"halifax": "≈250",
"fill": "Wreckspeditions, Dunoon (air, nitrox 32%); no helium locally – pre-arrange trimix",
"fillsite": "≈8",
"notes": "Sunk in a collision off Skelmorlie 1907. Sits upright & largely intact at ~48m – a classic Clyde technical wreck. Deep, dark and current-swept: slack water + decompression training required."
}
];

// ---------------- shared config ----------------
const TIDETIME={
 "Scapa Flow, Orkney":"stromness","Farne Islands, Northumberland":"seahouses","St Abbs & Eyemouth":"eyemouth",
 "Whitby, North Yorkshire":"whitby","Anglesey, North Wales":"holyhead","Whitsand Bay / Plymouth":"plymouth",
 "Portland & Weymouth, Dorset":"portland","Oban, Argyll":"oban","Sound of Mull (Lochaline)":"oban",
 "Plymouth Sound":"plymouth","Firth of Clyde":"greenock"};
const LAB=["GO","CAUTION","NO-GO"],CLS=["go","cau","no"];
const VCOL=["#22e39a","#ffcf4d","#ff5d6c"];
function esc(x){return String(x==null?"":x).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
function tideURL(r){return "https://www.tidetime.org/europe/united-kingdom/"+(TIDETIME[r]||"all")+".htm";}
function yrURL(s){return "https://www.yr.no/en/forecast/daily-table/"+s.lat+","+s.lon;}
function infoURL(s){var area=s.r.split(/[,(]/)[0].trim();return "https://www.google.com/search?q="+encodeURIComponent(s.n+" wreck "+area);}
function wreckURL(s){return "wreck.html?id="+s.slug;}
// ---------------- units ----------------
function getU(k,d){try{return localStorage.getItem(k)||d;}catch(e){return d;}}
function setU(k,v){try{localStorage.setItem(k,v);}catch(e){}}
function windU(){return getU("u_wind","kn");}
function waveU(){return getU("u_wave","m");}
function fmtWind(kn){if(kn==null)return "—";return windU()==="mph"?Math.round(kn*1.15078):kn;}
function fmtWave(m){if(m==null)return null;return waveU()==="ft"?(m*3.28084):m;}
function waveTxt(m){var v=fmtWave(m);return v==null?null:v.toFixed(waveU()==="ft"?1:1)+" "+waveU();}
// ---------------- astronomy / tide ----------------
const D2R=Math.PI/180;
function n360(x){x%=360;return x<0?x+360:x;}
function jdc(dt){return dt.getTime()/86400000+2440587.5-2451545.0;}
function moonRA(d){var L=n360(218.316+13.176396*d),M=(134.963+13.064993*d)*D2R,F=(93.272+13.229350*d)*D2R;
 var lon=(L+6.289*Math.sin(M))*D2R,lat=(5.128*Math.sin(F))*D2R,e=23.4397*D2R;
 return n360(Math.atan2(Math.sin(lon)*Math.cos(e)-Math.tan(lat)*Math.sin(e),Math.cos(lon))*180/Math.PI);}
function gmst(d){return n360(280.46061837+360.98564736629*d);}
function springFactor(dt){var d=jdc(dt);var De=n360(297.850+12.190749*d)*D2R;return Math.abs(Math.cos(De));}
function springLabel(dt){var sf=springFactor(dt);return sf>0.6?"Springs":sf<0.4?"Neaps":"Mid-range";}
function fmtDur(h){if(h<0)h+=12.4206;var m=Math.round(h*60);return m>=60?Math.floor(m/60)+"h "+(m%60)+"m":m+"m";}
function tidePhase(dt,lonEast,hwi){var d=jdc(dt),ra=moonRA(d),lst=n360(gmst(d)+lonEast);var H=n360(lst-ra);
 var hT=(H%180)/14.492;var hHW=((hT-hwi)%12.4206+12.4206)%12.4206;var x=hHW;if(x>6.2103)x-=12.4206;
 var ax=Math.abs(x);var nHW=12.4206-hHW;var nLW=6.2103-hHW;if(nLW<0)nLW+=12.4206;var toS=Math.min(nHW,nLW);
 var ph=(ax<1||Math.abs(ax-6.2103)<1)?"Slack":(x>0?"Ebbing":"Flooding");return {phase:ph,toSlack:toS};}
// ---------------- verdict / outlook ----------------
function verdict(gust,wave){var w=gust<=16?0:gust<=24?1:2;var s=(wave==null)?0:(wave<=0.8?0:(wave<=1.3?1:2));return Math.max(w,s);}
function outlook(fi,mi,curtime){
 if(!fi||!fi.hourly||!fi.hourly.time)return null;
 var ft=fi.hourly.time,fg=fi.hourly.wind_gusts_10m,key=curtime.slice(0,13);
 var idx=ft.findIndex(function(t){return t.slice(0,13)===key;});if(idx<0)idx=ft.findIndex(function(t){return t>=curtime;});if(idx<0)idx=0;
 var mt=(mi&&mi.hourly&&mi.hourly.time)?mi.hourly.time:null;var mw=(mi&&mi.hourly)?mi.hourly.wave_height:null;
 var midx=-1;if(mt){midx=mt.findIndex(function(t){return t.slice(0,13)===key;});if(midx<0)midx=mt.findIndex(function(t){return t>=curtime;});}
 var hrs=[];for(var h=0;h<12;h++){var gi=idx+h;if(gi>=ft.length)break;
  var gust=(fg[gi]!=null)?Math.round(fg[gi]):null;var wave=null;if(mt&&midx>=0&&(midx+h)<mw.length&&mw[midx+h]!=null)wave=mw[midx+h];
  var v=(gust==null)?3:verdict(gust,wave);hrs.push({t:ft[gi].slice(11,16),gust:gust,wave:wave,v:v});}
 return hrs;}
function computeConditions(s,Fi,Mi,now){
 var cur=(Fi&&Fi.current)?Fi.current:null,mar=(Mi&&Mi.current)?Mi.current:null;
 var gustKn=cur?Math.round(cur.wind_gusts_10m):null,windKn=cur?Math.round(cur.wind_speed_10m):null;
 var wave=(mar&&mar.wave_height!=null)?mar.wave_height:null;var hrs=cur?outlook(Fi,Mi,cur.time):null;
 var v,cls,lab,tideMain,tideSub,tcls;
 if(s.nd){v=-1;cls="nd";lab="NO DIVE";tideMain="—";tideSub="";tcls="";}
 else if(gustKn==null){v=3;cls="no";lab="—";tideMain="—";tideSub="";tcls="";}
 else{v=verdict(gustKn,wave);
  if(s.td==="none"){tideMain="Any state";tcls="ok";tideSub="";}
  else{var tp=tidePhase(now,s.lon,s.hwi);v=Math.max(v,1);tcls="slack";
   tideMain=(s.td==="essential"?"Slack essential":"Slack advised");tideSub=tp.phase+" · slack ~"+fmtDur(tp.toSlack)+" (est)";}
  cls=CLS[v];lab=LAB[v];}
 var sr=null,ss=null;if(Fi&&Fi.daily&&Fi.daily.sunrise){sr=Fi.daily.sunrise[0];ss=Fi.daily.sunset[0];}
 return {gustKn:gustKn,windKn:windKn,wave:wave,hrs:hrs,v:v,cls:cls,lab:lab,tideMain:tideMain,tideSub:tideSub,tcls:tcls,sunrise:sr,sunset:ss};
}
function hhmm(iso){if(!iso)return "—";return iso.slice(11,16);}
// ---------------- fetch ----------------
function asArr(d){return Array.isArray(d)?d:[d];}
function fetchJSON(u){return fetch(u).then(function(r){if(!r.ok)throw new Error("HTTP "+r.status);return r.json();});}
function fetchAll(days,subset){
 days=days||2;var list=subset||SITES;
 var lats=list.map(function(s){return s.lat;}).join(","),lons=list.map(function(s){return s.lon;}).join(",");
 var fUrl="https://api.open-meteo.com/v1/forecast?latitude="+lats+"&longitude="+lons+"&current=wind_speed_10m,wind_gusts_10m,weather_code&hourly=wind_speed_10m,wind_gusts_10m&daily=sunrise,sunset,wind_gusts_10m_max&wind_speed_unit=kn&forecast_days="+days+"&timezone=auto";
 var mUrl="https://marine-api.open-meteo.com/v1/marine?latitude="+lats+"&longitude="+lons+"&current=wave_height,swell_wave_height&hourly=wave_height&daily=wave_height_max&forecast_days="+days+"&timezone=auto";
 return Promise.allSettled([fetchJSON(fUrl),fetchJSON(mUrl)]).then(function(res){
  if(res[0].status!=="fulfilled")throw res[0].reason;
  var F=asArr(res[0].value),M=(res[1].status==="fulfilled")?asArr(res[1].value):[];
  return {F:F,M:M,now:new Date()};});
}


// ---------------- weather codes ----------------
const WMO={0:"Clear",1:"Mainly clear",2:"Partly cloudy",3:"Overcast",45:"Fog",48:"Rime fog",51:"Drizzle",53:"Drizzle",55:"Dense drizzle",56:"Freezing drizzle",57:"Freezing drizzle",61:"Light rain",63:"Rain",65:"Heavy rain",66:"Freezing rain",67:"Freezing rain",71:"Light snow",73:"Snow",75:"Heavy snow",77:"Snow grains",80:"Showers",81:"Showers",82:"Violent showers",85:"Snow showers",86:"Snow showers",95:"Thunderstorm",96:"Storm+hail",99:"Storm+hail"};
function wmo(c){return c==null?"—":(WMO[c]||("code "+c));}
const INLAND=[{"n": "Eccleston Delph ('The Delph')", "area": "Lancashire", "lat": 53.625, "lon": -2.72, "type": "Flooded stone quarry", "maxD": 14, "temp": "~18°C surface / ~5°C winter", "viz": "2–6m", "best": "Year-round", "attractions": "Speedboats, Jet Provost jet, APCs, concrete tube, training platforms", "facilities": "Air fills, café, dive shop, rental, reception, parking", "fills": "yes", "fillnote": "Air to 230 bar on site (~£10/cyl)", "access": "Open commercial site", "cost": "Entry fee (see website)", "booking": "No — within opening hours", "level": "Novice+ (great training)", "halifax": 45, "postcode": "PR7 5PR", "notes": "Close to Halifax (nr Chorley). Sat/Sun 9–4, Mon–Fri 10–3 (Tue/Wed also 17:30–21:00). Register on arrival.", "web": "https://www.thedelph.com/", "flag": ""}, {"n": "Eight Acre Lake", "area": "East Yorkshire", "lat": 53.77, "lon": -0.66, "type": "Spring-fed lake (dive & watersports centre)", "maxD": 14, "temp": "~17°C surface / ~5°C winter; cool at depth", "viz": "2–5m", "best": "Year-round", "attractions": "10 sunken wrecks, PUMA helicopter, swim-through pipes; sturgeon/trout/carp", "facilities": "Dive store, air fills, kit hire, changing, café (weekends Mar–Nov); school Scuba Dream on site", "fills": "yes", "fillnote": "Air on site (Scuba Dream)", "access": "Open commercial site", "cost": "~£20 diver entry (loyalty deals)", "booking": "Day entry or membership", "level": "Novice+ (excellent training)", "halifax": 50, "postcode": "HU15 2QP", "notes": "Closest managed site to Halifax (North Cave, near Hull, off A63). Yorkshire's main training lake.", "web": "https://www.8acre.com/", "flag": ""}, {"n": "Capernwray (Jackdaw Quarry)", "area": "Lancashire", "lat": 54.14, "lon": -2.75, "type": "Spring-fed limestone quarry", "maxD": 22, "temp": "~16–18°C surface / ~6–8°C deep", "viz": "up to 15m (spring-fed)", "best": "Year-round", "attractions": "Cessna & other aircraft, boats, Wessex helicopter, container 'cave', statues, sturgeon/trout", "facilities": "Dive shop, café/restaurant, changing, showers, parking", "fills": "yes", "fillnote": "Air & nitrox on site (Aqualung Gold Centre)", "access": "Open commercial site", "cost": "Day ticket (see website)", "booking": "Advisable — check hours", "level": "All levels; great training", "halifax": 55, "postcode": "LA6 1AD", "notes": "Widely rated the UK's finest freshwater dive site. Open Tue–Sun (Mon closed exc. BH).", "web": "https://www.dive-site.co.uk/", "flag": ""}, {"n": "Ellerton Park", "area": "North Yorkshire", "lat": 54.36, "lon": -1.626, "type": "Spring-fed lake (60 acres)", "maxD": 9, "temp": "~18°C surface / ~5°C winter", "viz": "1–4m (algae/silt dependent)", "best": "Year-round; best spring", "attractions": "Boats, concrete pipes, caravans, training platforms", "facilities": "Toilets, showers, changing; café; cash only", "fills": "no", "fillnote": "No on-site air — fill at Academy Divers, Halifax first", "access": "Open commercial site", "cost": "£10–11/day (cash)", "booking": "No — within opening hours", "level": "Novice+ (training)", "halifax": 58, "postcode": "DL10 6AR", "notes": "Open 7 days 9–5; late Tue/Thu to 19:30. Cash only.", "web": "https://www.ellertonpark.com/watersports", "flag": ""}, {"n": "Dosthill Quarry ('Dozzy')", "area": "Staffordshire", "lat": 52.6, "lon": -1.68, "type": "Flooded quarry — UK's oldest inland dive site", "maxD": 25, "temp": "~18°C surface / ~5–6°C winter; cold deep", "viz": "2–6m", "best": "Year-round", "attractions": "Training platforms, sunken structures", "facilities": "Café, parking; on-site air (check current)", "fills": "check", "fillnote": "On-site air — check current with the site", "access": "Open (opening hours)", "cost": "Entry fee (see website)", "booking": "No — within opening hours", "level": "All levels (deep section for qualified)", "halifax": 100, "postcode": "B77 5LX", "notes": "Open Wed–Fri 13:00–19:00, Sat/Sun 08:00–14:00 (some BHs). One of the UK's oldest inland dive sites.", "web": "https://www.dosthillquarry.com/", "flag": ""}, {"n": "Stoney Cove", "area": "Leicestershire", "lat": 52.552, "lon": -1.272, "type": "Flooded granite quarry — 'National Diving Centre'", "maxD": 36, "temp": "~18°C surface / ~6°C below thermocline", "viz": "3–8m", "best": "Year-round; viz best autumn–spring", "attractions": "Stanegarth tug (1910), Nautilus & Wessex, aircraft cockpit & more", "facilities": "Underwater World dive shop (air/nitrox/trimix), Nemo's café, Dive Inn pub, parking", "fills": "yes", "fillnote": "Air, nitrox & trimix on site (Underwater World)", "access": "Open commercial site", "cost": "Day ticket (see website)", "booking": "Not usually — arrive early in summer", "level": "All levels incl. technical", "halifax": 105, "postcode": "LE9 4DW", "notes": "UK's most popular inland site; very busy on summer weekends.", "web": "https://www.stoneycove.co.uk/", "flag": ""}, {"n": "Gildenburgh Water", "area": "Cambridgeshire", "lat": 52.554, "lon": -0.106, "type": "Spring-fed lake (6.5 acres)", "maxD": 22, "temp": "~18°C surface / ~6°C deep", "viz": "2–5m", "best": "Year-round", "attractions": "Double-decker bus, aeroplane, sunken 'wrecks', good fish life", "facilities": "Clubhouse, shop, air station, cylinder testing, rental (inc. drysuits) (Dive In Ltd)", "fills": "yes", "fillnote": "Air on site (air station)", "access": "Open commercial site", "cost": "£20/session", "booking": "Yes — book via diveandswim.online", "level": "Novice+ (training/refreshers)", "halifax": 120, "postcode": "PE7 2AR", "notes": "7 miles from Peterborough. Open 7 days 8–4, late Fri. Sat-nav may misdirect — use their own map.", "web": "https://gildenburgh.com/", "flag": ""}, {"n": "Vivian Quarry", "area": "Gwynedd, North Wales", "lat": 53.123, "lon": -4.114, "type": "Flooded slate quarry", "maxD": 18, "temp": "~14–17°C surface / ~5°C winter, cold", "viz": "Good (slate walls)", "best": "Year-round", "attractions": "Mini submarine, mining relics, 10-ton winch, gnome garden, eels/trout", "facilities": "Run by Scuba Scape; parking £4 at Padarn Country Park; café at Slate Museum", "fills": "check", "fillnote": "Check with Scuba Scape (nearest N Wales dive shops otherwise)", "access": "Open — paid entry", "cost": "£10 entry + £15 annual membership; £4 parking", "booking": "Check Scuba Scape", "level": "Ocean Diver / novice+", "halifax": 135, "postcode": "LL55 4TY", "notes": "Dramatic vertical slate walls to ~18m. New underwater museum/experiences (2025) for non-divers age 10+.", "web": "https://www.scubascape.world/", "flag": ""}, {"n": "Cromhall Quarry ('The Lake')", "area": "South Gloucestershire", "lat": 51.62, "lon": -2.443, "type": "Flooded limestone quarry (2.7 ha)", "maxD": 17, "temp": "~18°C surface / ~6–8°C deep", "viz": "Good (limestone-filtered)", "best": "Year-round (weekends)", "attractions": "Light aircraft, sunken boats, training platforms", "facilities": "Managed by SW Maritime Academy; parking; limited", "fills": "no", "fillnote": "No public on-site fills — fill before arrival", "access": "Open on booked sessions", "cost": "£16–20/session", "booking": "Yes — pre-book (cromhallquarry.com)", "level": "All levels; SSSI", "halifax": 185, "postcode": "GL12 8AA", "notes": "Old 'Cromhall Dive Centre' CLOSED 2020 → now 'The Lake' under SWMA. Sat/Sun 08:30–16:30.", "web": "https://thelakeuk.com/activities/scuba-diving/", "flag": ""}, {"n": "Wraysbury Dive Centre", "area": "Berkshire", "lat": 51.46, "lon": -0.548, "type": "Flooded gravel-pit lake (15 acres)", "maxD": 12, "temp": "~18°C surface / ~5°C winter", "viz": "1–4m (silty)", "best": "Year-round", "attractions": "Sunken boats & training items; SE schools' training lake", "facilities": "Air fills, changing, café, shop, parking", "fills": "yes", "fillnote": "Air on site", "access": "Open commercial site", "cost": "£15 entry (cash only)", "booking": "No — Tue–Sun from 9am", "level": "Novice+ (training)", "halifax": 215, "postcode": "TW19 5ND", "notes": "London & SE's only dedicated inland dive site; M25 J13–14; 2-min walk from Wraysbury station. Closed Mondays (exc. BH).", "web": "https://www.wraysbury.ws/", "flag": ""}, {"n": "Vobster Quay", "area": "Somerset", "lat": 51.262, "lon": -2.42, "type": "Flooded quarry lake (36 acres)", "maxD": 40, "temp": "~18°C surface / ~6°C deep", "viz": "3–8m", "best": "Year-round", "attractions": "Sunken structures, boats, aircraft, platforms; technical-friendly", "facilities": "Air fills, changing, showers, café, parking", "fills": "yes", "fillnote": "Air on site", "access": "Members-only + weekly non-member Tuesday", "cost": "Membership / non-member Tue", "booking": "Pre-book (app.vobster.com); MEMBERS-ONLY exc. non-member Tue 08:00–15:00 (to end Sep 2026)", "level": "All levels incl. technical", "halifax": 225, "postcode": "BA3 5UH", "notes": "Now members-only; don't just turn up. (Nov 2024: SW corner closed after tree slippage — check notices.)", "web": "https://www.vobster.com/dive", "flag": ""}, {"n": "Wastwater (Wast Water)", "area": "Cumbria (Lake District)", "lat": 54.44, "lon": -3.3, "type": "Natural glacial lake — England's deepest", "maxD": 79, "temp": "~10–14°C surface / ~5–6°C deep, cold year-round", "viz": "Very clear (10–15m+) but dark deep", "best": "Settled weather only", "attractions": "England's deepest lake; dramatic screes; infamous 'gnome garden' at depth", "facilities": "NONE — National Trust shore; no fills/facilities/rescue", "fills": "no", "fillnote": "None on site — self-sufficient", "access": "Open natural site (free) — advanced", "cost": "Free (National Trust parking nearby)", "booking": "No", "level": "EXPERIENCED — deep & cold; shallow margins only for novices", "halifax": 130, "postcode": "CA20 1EX", "notes": "⚠ England's deepest lake (~79m). Cold, very clear (false sense of security) with a fatality history — divers lured deep to the 'gnome garden' (~48m). ~50m air-diver limit; below is technical. Shallow shore diving is fine — the DEPTH is the danger.", "web": "", "flag": "wild"}, {"n": "Hodge Close Quarry", "area": "Cumbria (Lake District)", "lat": 54.38, "lon": -3.05, "type": "Flooded slate quarry (UNMANAGED)", "maxD": 30, "temp": "~10°C surface / ~5–6°C deep, cold; altitude dive", "viz": "~10m (clear but dark)", "best": "Settled weather only", "attractions": "Rock arch & tunnels, wrecked cars, slate walls", "facilities": "NONE — remote; informal access via the house (~£4–5/car); no fills or rescue", "fills": "no", "fillnote": "None on site — self-sufficient", "access": "Unmanaged / informal — dive at own risk", "cost": "~£4–5 per car (at the house)", "booking": "No — owners don't formally permit; at own risk", "level": "EXPERIENCED (altitude, cold; 23m tunnels for overhead-qualified only)", "halifax": 115, "postcode": "LA21 8DZ", "notes": "⚠ Wild unmanaged site with a history of fatalities. Altitude dive (~155m ASL), cold year-round. Difficult access & extraction. Tunnels for trained overhead divers only.", "web": "", "flag": "wild"}, {"n": "Dorothea Quarry", "area": "Gwynedd, North Wales", "lat": 53.05, "lon": -4.22, "type": "Flooded slate quarry (NWTD-licensed)", "maxD": 106, "temp": "~14–18°C surface / ~6°C deep, colder deeper", "viz": "Variable — often good, dark deep", "best": "Sat/Sun club diving; settled weather", "attractions": "Slate walls, submerged machinery & trees, 104m tunnel", "facilities": "Run by North Wales Technical Divers (BSAC branch) under licence; no public fills", "fills": "no", "fillnote": "None on site — self-sufficient (mixed gas)", "access": "MEMBERS-ONLY via NWTD licence — not open to the public", "cost": "£25 NWTD club fee + access", "booking": "Join NWTD (nwtd.co.uk); qualified technical divers only", "level": "TECHNICAL ONLY — deco/mixed-gas (≥40m cert) + cold-water", "halifax": 135, "postcode": "LL54 6HY", "notes": "⚠ Formerly BANNED after many fatalities; since 2021 run by NWTD under exclusive licence — members only, NO public/turn-up access. A diver died at 85m here in June 2025.", "web": "https://www.nwtd.co.uk/", "flag": "restricted"}, {"n": "NDAC Chepstow — PERMANENTLY CLOSED", "area": "Gloucestershire (Chepstow)", "lat": 51.683, "lon": -2.66, "type": "Flooded quarry (~80m) — closed since 2022", "maxD": 80, "temp": "—", "viz": "—", "best": "—", "attractions": "(Formerly) aircraft, armoured vehicles, boats, helicopters", "facilities": "CLOSED since Feb 2022", "fills": "no", "fillnote": "Closed", "access": "CLOSED — not open to the public", "cost": "—", "booking": "CLOSED — not taking public/leisure bookings", "level": "CLOSED", "halifax": 200, "postcode": "NP16 7LH", "notes": "⚠ PERMANENTLY CLOSED Feb 2022. Listed because many guides STILL show it as open. Operator now runs NDAC TRF at Ammanford (124m) — TRAINING ORGANISATIONS ONLY, not recreational.", "web": "https://www.ndac.co.uk/", "flag": "closed"}];
